# Generated by Django 5.0.7 on 2024-07-17 11:15

# import datetime
# import django.db.models.deletion
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('classperiod', '0001_initial'),
#         ('classroom', '0001_initial'),
#         ('course', '0001_initial'),
#     ]

#     operations = [
#         migrations.RemoveField(
#             model_name='classperiod',
#             name='course_level',
#         ),
#         migrations.RemoveField(
#             model_name='classperiod',
#             name='day_of_week',
#         ),
#         migrations.RemoveField(
#             model_name='classperiod',
#             name='semester',
#         ),
#         migrations.RemoveField(
#             model_name='classperiod',
#             name='teacher',
#         ),
#         migrations.RemoveField(
#             model_name='classperiod',
#             name='year',
#         ),
#         migrations.AddField(
#             model_name='classperiod',
#             name='day_of_the_week',
#             field=models.CharField(default='14:09', max_length=10),
#             preserve_default=False,
#         ),
#         migrations.AddField(
#             model_name='classperiod',
#             name='name',
#             field=models.CharField(default=datetime.datetime(2024, 7, 17, 11, 15, 13, 215336), max_length=255),
#             preserve_default=False,
#         ),
#         migrations.AddField(
#             model_name='classperiod',
#             name='updated_at',
#             field=models.DateTimeField(auto_now=True),
#         ),
#         migrations.AlterField(
#             model_name='classperiod',
#             name='classroom',
#             field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.class'),
#         ),
#         migrations.AlterField(
#             model_name='classperiod',
#             name='course',
#             field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
#         ),
#         migrations.AlterField(
#             model_name='classperiod',
#             name='end_time',
#             field=models.DateTimeField(),
#         ),
#         migrations.AlterField(
#             model_name='classperiod',
#             name='id',
#             field=models.AutoField(primary_key=True, serialize=False),
#         ),
#         migrations.AlterField(
#             model_name='classperiod',
#             name='start_time',
#             field=models.DateTimeField(),
#         ),
#          migrations.AlterField(
#             model_name='your_model_name',
#             name='end_time',
#             field=models.DateTimeField(null=True),  
#         ),
#         migrations.AlterField(
#             model_name='your_model_name',
#             name='end_time',
#             field=models.DateTimeField(null=True, db_index=True),  
#         ),
#     ]

import datetime
import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):
    dependencies = [
        ('classperiod', '0001_initial'),
        ('classroom', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classperiod',
            name='course_level',
        ),
        migrations.RemoveField(
            model_name='classperiod',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='classperiod',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='classperiod',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='classperiod',
            name='year',
        ),
        migrations.AddField(
            model_name='classperiod',
            name='day_of_the_week',
            field=models.CharField(default='Monday', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classperiod',
            name='name',
            field=models.CharField(default='Class Period', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classperiod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.class'),
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RunSQL(
            sql=[
                # Step 1: Convert to timestamp without time zone
                "ALTER TABLE classperiod_classperiod ALTER COLUMN start_time TYPE timestamp without time zone USING (current_date + start_time)",
                "ALTER TABLE classperiod_classperiod ALTER COLUMN end_time TYPE timestamp without time zone USING (current_date + end_time)",
                
                # Step 2: Convert to timestamp with time zone
                "ALTER TABLE classperiod_classperiod ALTER COLUMN start_time TYPE timestamp with time zone",
                "ALTER TABLE classperiod_classperiod ALTER COLUMN end_time TYPE timestamp with time zone",
            ],
            reverse_sql=[
                "ALTER TABLE classperiod_classperiod ALTER COLUMN start_time TYPE time without time zone USING start_time::time",
                "ALTER TABLE classperiod_classperiod ALTER COLUMN end_time TYPE time without time zone USING end_time::time",
            ]
        ),
    ]