# Generated by Django 5.0.7 on 2024-07-17 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0002_remove_classperiod_course_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classperiod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 17, 11, 16, 42, 849645)),
            preserve_default=False,
        ),
    ]
