# Generated by Django 5.0.7 on 2024-07-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0003_classperiod_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classperiod',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
