# # Generated by Django 5.0.7 on 2024-07-21 18:01

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('classperiod', '0004_alter_classperiod_end_time'),
#     ]

#     operations = [
#         migrations.AlterField(
#             model_name='classperiod',
#             name='start_time',
#             field=models.DateTimeField(),
#         ),
#     ]

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('classperiod', '0001_initial'),  # Make sure this points to your last successful migration
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # Step 1: Convert to timestamp without time zone
                "ALTER TABLE classperiod_classperiod ALTER COLUMN start_time TYPE timestamp without time zone USING (current_date + start_time)",
                "ALTER TABLE classperiod_classperiod ALTER COLUMN end_time TYPE timestamp without time zone USING (current_date + end_time)",
                
                # Step 2: Convert to timestamp with time zone
                "ALTER TABLE classperiod_classperiod ALTER COLUMN start_time TYPE timestamp with time zone",
                "ALTER TABLE classperiod_classperiod ALTER COLUMN end_time TYPE timestamp with time zone",
            ],
            reverse_sql=[
                "ALTER TABLE classperiod_classperiod ALTER COLUMN start_time TYPE time without time zone USING start_time::time",
                "ALTER TABLE classperiod_classperiod ALTER COLUMN end_time TYPE time without time zone USING end_time::time",
            ]
        ),
    ]