# Generated by Django 5.0.7 on 2024-07-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0004_alter_classperiod_end_time'),
        ('classperiod', '0005_alter_classperiod_start_time'),
    ]

    operations = [
    ]
