# Generated by Django 5.0.7 on 2024-07-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0006_merge_20240721_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classperiod',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
