# Generated by Django 5.0.7 on 2024-07-21 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0007_alter_classperiod_start_time'),
        ('classperiod', '0008_description_of_migration'),
    ]

    operations = [
    ]
